-- Tabla principal para la HILU Administrativa (puede agrupar todas las fases o estar separada)
-- Por simplicidad y eficiencia, crearemos una sola tabla para HILU Administrativa que contendrá las tres fases.

CREATE TABLE IF NOT EXISTS public.hilu_administrativa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empleado_id BIGINT REFERENCES public.empleados(id) ON DELETE CASCADE,
    cargo VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_by BIGINT REFERENCES public.usuarios(id),
    
    -- FASE H: Inducción e incorporación a Firplak
    fh_induccion_th BOOLEAN DEFAULT FALSE,
    fh_induccion_sst BOOLEAN DEFAULT FALSE,
    fh_presentacion_area BOOLEAN DEFAULT FALSE,
    fh_explicacion_cargo BOOLEAN DEFAULT FALSE,
    fh_comentarios TEXT,
    fh_firma_empleado BOOLEAN DEFAULT FALSE,
    fh_firma_jefe BOOLEAN DEFAULT FALSE,
    fh_completado BOOLEAN DEFAULT FALSE,
    fh_fecha_finalizacion TIMESTAMP WITH TIME ZONE,

    -- FASE I: Entrenamiento y Capacitación del Cargo
    fi_capacitacion_funciones BOOLEAN DEFAULT FALSE,
    fi_capacitacion_procesos BOOLEAN DEFAULT FALSE,
    fi_capacitacion_herramientas BOOLEAN DEFAULT FALSE,
    fi_acompanamiento_practico BOOLEAN DEFAULT FALSE,
    fi_comentarios TEXT,
    fi_eval_actitud INTEGER CHECK (fi_eval_actitud BETWEEN 1 AND 5),
    fi_eval_adaptacion INTEGER CHECK (fi_eval_adaptacion BETWEEN 1 AND 5),
    fi_eval_aprendizaje INTEGER CHECK (fi_eval_aprendizaje BETWEEN 1 AND 5),
    fi_eval_conocimiento INTEGER CHECK (fi_eval_conocimiento BETWEEN 1 AND 5),
    fi_completado BOOLEAN DEFAULT FALSE,
    fi_fecha_finalizacion TIMESTAMP WITH TIME ZONE,

    -- FASE L: Validación en el cargo
    fl_desempena_autonomia BOOLEAN DEFAULT FALSE,
    fl_cumple_responsabilidades BOOLEAN DEFAULT FALSE,
    fl_aplica_procedimientos BOOLEAN DEFAULT FALSE,
    fl_ejecuta_sin_acompanamiento BOOLEAN DEFAULT FALSE,
    fl_cumple_resultados BOOLEAN DEFAULT FALSE,
    fl_comentarios TEXT,
    fl_firma_empleado BOOLEAN DEFAULT FALSE,
    fl_firma_jefe BOOLEAN DEFAULT FALSE,
    fl_completado BOOLEAN DEFAULT FALSE,
    fl_fecha_finalizacion TIMESTAMP WITH TIME ZONE,
    
    UNIQUE(empleado_id, cargo)
);

-- Políticas de RLS (Opcional, según cómo lo manejes en tu proyecto)
ALTER TABLE public.hilu_administrativa ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acceso total para usuarios autenticados" ON public.hilu_administrativa
    FOR ALL
    USING (auth.role() = 'authenticated')
    WITH CHECK (auth.role() = 'authenticated');
